# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_name', models.CharField(max_length=200)),
                ('ticket_room', models.CharField(max_length=200)),
                ('ticket_sum', models.CharField(max_length=200)),
                ('ticket_descr', models.TextField(default='Add your super descriptive text here...', verbose_name='Descriptive text')),
            ],
        ),
    ]
