# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 11:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hwform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 13, 11, 13, 5, 580696, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
    ]
